version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: postgres # Default database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: go-app
    depends_on:
      - postgres
    environment:
      DB_USER: postgres        # Default user
      DB_PASSWORD: ""          # No password
      DB_NAME: postgres        # Default database
      DB_HOST: postgres
      DB_PORT: 5432
      DB_SSLMODE: disable
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  postgres-data:
